# note: the compose project name will be overridden by the distr agent, to create a unique name
name: hello-distr

# note: only share non-sensitive data to avoid accidental exposure of sensitive values (like passwords) to other containers
x-shared-env: &shared-env
  HELLO_DISTR_HOST: ${HELLO_DISTR_HOST:?error}
  HELLO_DISTR_PROTOCOL: ${HELLO_DISTR_PROTOCOL:-http}
  HELLO_DISTR_DB_NAME: ${HELLO_DISTR_DB_NAME:?error}

x-default-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  postgres:
    image: "postgres:18.4-alpine3.23"
    logging: *default-logging
    environment:
      <<: *shared-env
      POSTGRES_USER: ${HELLO_DISTR_DB_USER:?error}
      POSTGRES_PASSWORD: ${HELLO_DISTR_DB_PASSWORD:?error}
      POSTGRES_DB: ${HELLO_DISTR_DB_NAME:?error}
    healthcheck:
      test: pg_isready -h localhost -U ${HELLO_DISTR_DB_USER:?error} -d ${HELLO_DISTR_DB_NAME:?error}
      interval: 5s
    volumes:
      - "postgres:/var/lib/postgresql/"
    networks:
      - app_network

  backend:
    image: registry.distr.sh/subconscious/hello-distr/backend:0.5.2 # x-release-please-version
    logging: *default-logging
    environment:
      <<: *shared-env
      DB_URL: postgresql://${HELLO_DISTR_DB_USER:?error}:${HELLO_DISTR_DB_PASSWORD:?error}@postgres/${HELLO_DISTR_DB_NAME:?error}?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:5000/health', timeout=1)",
        ]
      interval: 5s
    networks:
      - app_network

  frontend:
    image: registry.distr.sh/subconscious/hello-distr/frontend:0.5.2 # x-release-please-version
    logging: *default-logging
    environment:
      <<: *shared-env
      NEXT_PUBLIC_API_URL: "${HELLO_DISTR_PROTOCOL:-http}://${HELLO_DISTR_HOST:?error}/api"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://127.0.0.1:3000"]
      interval: 5s
    extra_hosts:
      - "${HELLO_DISTR_HOST:?error}=host-gateway"
    networks:
      - app_network

  proxy:
    image: registry.distr.sh/subconscious/hello-distr/proxy:0.5.2 # x-release-please-version
    logging: *default-logging
    environment:
      <<: *shared-env
      HOST: ${HELLO_DISTR_HOST:?error}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://127.0.0.1:80"]
      interval: 5s
    networks:
      - app_network

  jobs:
    image: registry.distr.sh/subconscious/hello-distr/jobs:0.5.2 # x-release-please-version
    logging: *default-logging
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "pgrep", "busybox"]
      interval: 5s
    networks:
      - app_network

volumes:
  postgres:

networks:
  app_network:
    driver: bridge
